apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: i14zuy9ar-go 
  janus-idp.io/tekton: i14zuy9ar-go
  backstage.io/kubernetes-id: i14zuy9ar-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i14zuy9ar-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml