apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: i14zuy9ar-go
  janus-idp.io/tekton: i14zuy9ar-go
  backstage.io/kubernetes-id: i14zuy9ar-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i14zuy9ar-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
